# Generated by Django 3.2.7 on 2021-09-26 12:19

from django.db import migrations, models
import gitload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitloadToken',
            fields=[
                ('value', models.TextField(default=gitload.models.generate_token_value, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
