# Generated by Django 3.2.7 on 2021-09-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=60)),
                ('description', models.TextField(max_length=200)),
                ('markdown', models.TextField()),
                ('authors', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
